### ISSUE TITLE
VLC-Qt Error: libvlc failed to load!

### ISSUE THREAD

**Issue by abhay44** [vlc-qt/vlc-qt#179]
Hello!I tried deploying a customized media player using vlc-qt.Once the deployment is done,when I open the appimage it throws the following error.
`[0000000001ce8b98] core libvlc error: No plugins found! Check your VLC installation.
VLC-Qt Error: libvlc failed to load!
Segmentation fault
`
Is it a bug?am I doing something wrong?Can anybody suggest a solution for this?

**Comment by ntadej** [comment]
Please provide OS, compiler, VLC, VLC-Qt versions ...

**Comment by abhay44** [comment]
I am using linuxmint,compiler is gcc64bit and these are the vlc,vlc-qt versions 
`VLC-Qt "1.1.0" initialised
Using libvlc version: "2.2.5 Weatherwax"`

**Comment by ntadej** [comment]
You can set plugin path using [VlcCommon::setPluginPath](https://vlc-qt.tano.si/reference/1.1/namespaceVlcCommon.html#ab213a4062a1afeb7d87bfa608515f8f6).

**Comment by abhay44** [comment]
Can you explain more briefly how to set this pluginpath? Thanks!

**Comment by ntadej** [comment]
You call this function before initialising VlcInstance. It will set an environment variable with the plugin path.

**Comment by abhay44** [comment]
I placed the pluginpath as you said.I can run the app in my Qt creator and in the build version also.But the same error occurs while I am deploying it.What may be the problem?Do I need to download any plugins manually and place it inside the folder(vlc plugins)?If yes,can you tell me which plugins and where to place them?Thanks!

**Comment by ntadej** [comment]
How do you deploy your app?

**Comment by abhay44** [comment]
I am deploying my app by linuxdeployqt tool

**Comment by ntadej** [comment]
I think linuxdeployqt tool is not supported for VLC based applications (at least I do not use it). You need to create a proper package for your distribution or use static VLC build.

**Comment by abhay44** [comment]
Can you please briefly tell me how to create a proper package?

**Comment by abhay44** [comment]
Solved this issue.I have to export the vlc plugin path.That's it! Thanks for your suggestion :)

**Comment by xcodevsci** [comment]
abhay44  please explain how have u export vlc plugin path? Can u explain ?

**Comment by tonkatsulink** [comment]
According to the author, when I use the **_linuxdeployqt_** tool to deploy my software and then migrate it to another machine without VLC environment, it will report an error: `core libvlc error: no plugins found! Check your VLC installation.`. 
This is my solution: 
**1.** I copy all the contents under `/usr/lib/vlc/plugins/` in the development environment to the `plugins/` folder generated by the **_linuxdeployqt_** tool; 
**2.** I made a _**.sh**_ file and placed it in the software path. In the file, I first set the temporary environment variable: `export VLC_ PLUGIN_ Path = /opt/software/plugins/` (Note: `/opt/software/` is the path to deploy the software), and then run the software program: `/opt/software/main`;
**3.** Execute the **_.sh_** file.

I see that this problem came out a long time ago. Questioner, you may have solved this problem. However, since I am developing QT VLC related software recently, I specially record this problem here. If other developers encounter the same problem and query here, I hope my scheme can help you. Thank you!
