### ISSUE TITLE
Help QT VLC 

### ISSUE THREAD

**Issue by BadHermano** [vlc-qt/vlc-qt#228]
Hi :slight_smile:
i need some help setting up VLC - QT. (Windows 10)
I tried several tutorials but i didn’t get it running
What i 've done so far:

downloaded https://vlc-qt.tano.si/ this Windows 32-bit (MinGW)
Then i downloaded an example (simple-Player) from GIT) https://github.com/vlc-qt/examples
Then i imported my path to the library in the .pro file
LIBS += -LC:\Qt\libvlc-qt\lib -llibVLCQtCore -llibVLCQtWidgets
INCLUDEPATH += C:\Qt\libvlc-qt\include
I also copied the Plugins from the VLC folder to the Player
VlcCommon::setPluginPath(“C:/Qt/libvlc-qt/plugins”);
My Problem is that if i run the project (debug) minGW the .exe crashed
C:\Users\Giova\Desktop\examples-master\build-simple-player-Desktop_Qt_5_9_2_MinGW_32bit-Debug\src\debug\simple-player.exe crashed.

Has anybody an ideo what i could do ?

**Comment by shbobur** [comment]
Hi, 
In my case also it crashed because of different reasons. 
Try this: if you are building a debug then copy all debug libraries (ends with *d.dll) to the folder where simple-player.exe is located and try to run by double-clicking on it. If you're building release then copy release libraries.
Hope this helps!

**Comment by BadHermano** [comment]
Yes this was the solution ... Thanky you very much !

**Comment by shbobur** [comment]
Glad it helped. You may close this issue.
