### ISSUE TITLE
vlc-qt usable from MSVC2013?

### ISSUE THREAD

**Issue by maximus321** [vlc-qt/vlc-qt#43]
Hi,

I would like to know if there are plan to make a VS 2013 version of vlc-qt
My app is now compiled with :
Qt 5.3.1 for Windows 32-bit (VS 2013, 559 MB) 
And i'm having trouble using vlc-qt ,

Thank you!

**Comment by maximus321** [comment]
Hey there, just wanted a quick update on the MSVC2013 release.  I would like to use MSVC2013 since QWebEngine required MSVC2013 on Windows (not usable with MSVC 2012) - This is with the latest Qt 5.4, Thanks a lot

**Comment by dkomer** [comment]
I  followed this and I get: error LNK1107: invalid or corrupt file: cannot read at 0x12	c:\Program Files (x86)\VideoLAN\VLC\sdk\lib\vlc.lib

**Comment by ntadej** [comment]
Run `win_vlc_symbols_win32.bat` in the VLC directory. Will be added to readme.

**Comment by dkomer** [comment]
Hmmm... I'm hot on the trail that you took too, via https://wiki.videolan.org/GenerateLibFromDll/

:)

It's giving me some corrupted output though (not your tool, just when I tried running those commands by hand)... This also solves the problem of the exe installer not supplying .lib, but then need to still grab "include" dir from zip download...one sec, will try...

**Comment by dkomer** [comment]
closer... no more vlc error at the beginning. yay! now it's telling me that qt is x64 and conflicts with the other stuff which is x32... I guess I need to use vlc 64 bit and get libs from there? any problems with that?

**Comment by ntadej** [comment]
No, I build for both architectures without any problems.

**Comment by maximus321** [comment]
The nightly builds are a blessing, you can use the build made by ntadej to save some time. Forgot the URL.. Thanks ntadej for his hard work on this.

**Comment by dkomer** [comment]
ok... well I got build succeeded!

Then when I try to build the simple player example project, it builds too!

Then running it crashes :(

Nightly build for msvc2013 that I can just drop into qt creator and build/run sample project would be extremely helpful!

Or, here's what I did... maybe you can spot the mistake:

1) install VLC 32 bit from site (recommended install)
2) install, and copy vlccorelib.dll and vlc.dll to some other place for safety
3) download VLC 7zip version for windows, just to grab include directory from there (exe install is currently missing this) and copy that to same place you put the dlls (I call it dependencies, fwiw)
4) Follow instructions at https://wiki.videolan.org/GenerateLibFromDll/ to extract .lib from .dll. or use automatic way with tool in qt-vlc, but I could not because it gets corrupted somehow. I use notepad++ and record a macro, took about 1 min to zoom through the files. Also- replace x86 with x64
5) run cmake as above, but use visual studio 2013 64 bit (not just 2013)
6) for vlc stuff, point to the include and .libs
7) open .sln in visual studio and build
8) It will succeed! (hopefully)
9) grab all the *.lib and *.exp from there (i.e. src/core/vlc-qt.lib) and copy out to final release directory
10) make include directory, and copy Config.h to there
11) make vlc-qt directory in there, and copy all *.h from original vlc-qt directory to it (i.e. not from cmake project folder)
12) in qt creator, update library and include paths to include these
13) for running, copied all *.dll from Qt (for testing), as well as *.dll in vlc-qt and libvlc

**Comment by dkomer** [comment]
@maximus321  - did you happen to find the url for nightly builds?

**Comment by maximus321** [comment]
It used to be 
http://download.tano.si/
Not sure if it exists anymore, let me know if you need hosting ntadej, I have a VPS that could host.. thanks!

**Comment by ntadej** [comment]
I broke the config when moving some files. It should work now :)

**Comment by filipdns** [comment]
Hello, trying to compile vlc-qt I have some error, like poll identifier and nowhere I can found windows folder like wawa19933 say or poll.h...

C:\Program Files (x86)\VideoLAN\VLC\sdk\include\vlc\plugins\vlc_threads.h:90: erreur : C3861: 'poll': identifier not found

**Comment by tudodetalhado** [comment]
Hi filipdns, did you find any solution?

**Comment by tudodetalhado** [comment]
Finally, the compilation succeed.

From version 0.10.0 to 0.90.0 the _vlc-qt\windows\poll.h_ was removed, but to windows compilation it is still necessary. I got it from here https://github.com/vlc-qt/vlc-qt/tree/0.10.0/windows/msvc, then I put the #include <poll.h> in the _vlc_threads.h_.  

When compiling I also got the error _vlc.lib_ and _vlccore.lib_ invalid or corrupted. Then I deleted both and renamed the _libvlc.lib_ and _libvlccore.lib_ as _vlc.lib_ and _vlccore.lib_ and the compilation occour correctly.
